import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {motion, AnimatePresence} from 'framer-motion';
import './styles.css';

const books=[{id:1,title:'«Марина до …»',type:'Роман · книга первая трилогии',description:'О зависимости от мнений, норм, отношений и собственных эмоций.',price:'490 ₽',excerpt:'Героиня оказывается внутри пространства собственных ожиданий — и постепенно учится слышать себя.',cover:'МАРИНА\nДО …'}];
const events=[{date:'18',month:'октября',time:'19:00',title:'Творческий вечер «Марина до …»',place:'Театральное пространство, Париж',text:'Презентация книги с чтением отрывков и беседой с автором.'},{date:'02',month:'ноября',time:'18:30',title:'Творческая встреча',place:'Париж',text:'Разговор о литературе, эмиграции и новых авторских проектах.'}];
const fade={hidden:{opacity:0,y:24},show:{opacity:1,y:0,transition:{duration:.65}}};

function App(){
 const [menu,setMenu]=useState(false), [book,setBook]=useState(null), [form,setForm]=useState(false), [sent,setSent]=useState(false);
 const go=id=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMenu(false)};
 return <div className="site">
  <header className="header"><a className="logo" onClick={()=>go('top')}>Анастасия<br/><span>Алексеевна</span></a><button className="burger" onClick={()=>setMenu(!menu)} aria-label="Меню">☰</button><nav className={menu?'nav open':'nav'}>{[['about','Обо мне'],['books','Книги'],['events','Мероприятия'],['gallery','Галерея'],['contact','Контакты']].map(([id,t])=><button key={id} onClick={()=>go(id)}>{t}</button>)}</nav><button className="nav-cta" onClick={()=>go('books')}>Книги</button></header>
  <main id="top">
   <section className="hero"><div className="hero-copy"><p className="eyebrow">ЛИТЕРАТУРНОЕ ПРОСТРАНСТВО АВТОРА</p><motion.h1 initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{duration:.8}}>Анастасия<br/><i>Алексеевна</i></motion.h1><p className="lead">Писатель · поэт · автор сценариев<br/>и театральных проектов</p><blockquote>«Читайте. Слушайте. Приходите в театр.<br/>Оставайтесь в этой истории.»</blockquote><div className="actions"><button className="btn primary" onClick={()=>go('books')}>Книги</button><button className="btn ghost" onClick={()=>go('events')}>Мероприятия</button></div></div><div className="hero-photo"><div className="photo-placeholder"><span>ФОТО<br/>АВТОРА</span></div></div></section>
   <motion.section id="about" className="section about" variants={fade} initial="hidden" whileInView="show" viewport={{once:true}}><div className="section-label">01 · ОБ АВТОРЕ</div><div><h2>Путь от провинциального репортёра до писателя</h2><div className="bio-grid"><p><b>Детство</b><br/>Родилась в закрытом военном городке СССР; юность пришлась на девяностые годы.</p><p><b>Начало пути</b><br/>Ранняя репортёрская деятельность на региональном уровне — темы молодёжи и провинции.</p><p><b>Эмиграция</b><br/>Переезд во Францию и путь интеграции во французское общество.</p><p><b>Возвращение к письму</b><br/>Первая книга трилогии «Марина до …» — о зависимости от мнений, норм и эмоций.</p></div></div></motion.section>
   <section id="books" className="section books"><div className="section-label">02 · КНИГИ</div><div className="book-layout"><div className="book-cover"><div><small>РОМАН</small><strong>МАРИНА<br/>ДО …</strong><em>книга первая трилогии</em></div></div><div className="book-info"><p className="eyebrow">КНИГА ПЕРВАЯ ТРИЛОГИИ</p><h2>«Марина до …»</h2><p>О зависимости от мнений, норм, отношений и собственных эмоций.</p><button className="text-link" onClick={()=>setBook(books[0])}>Прочитать отрывок →</button><div className="purchase"><div><span>Электронная книга</span><b>490 ₽</b></div><button className="btn primary" onClick={()=>setBook(books[0])}>Купить</button></div><div className="formats"><span>EPUB · смартфон / планшет / e-reader</span><span>PDF · ноутбук / компьютер / планшет</span><span>MOBI · электронная книга</span></div></div></div></section>
   <section id="events" className="section events"><div className="section-label">03 · АФИША</div><div className="events-head"><div><h2>Приходите в эту историю</h2><p>Спектакли, презентации, чтения и творческие встречи.</p></div><button className="btn ghost" onClick={()=>setForm(true)}>Предложить встречу</button></div><div className="event-list">{events.map((e,i)=><motion.article className="event" key={i} whileHover={{x:8}}><div className="event-date"><strong>{e.date}</strong><span>{e.month}</span></div><div><h3>{e.title}</h3><p>{e.time} · {e.place}</p><small>{e.text}</small></div><button className="text-link" onClick={()=>setForm(true)}>Забронировать →</button></motion.article>)}</div></section>
   <section id="gallery" className="section gallery"><div className="section-label">04 · ФОТОГАЛЕРЕЯ</div><h2>За кулисами</h2><div className="masonry">{['Спектакли','Репетиции','Презентации','Автор за работой','Творческие встречи','Концерты'].map((x,i)=><div className={'gallery-item g'+(i+1)} key={x}><span>{x}</span></div>)}</div></section>
   <section className="section project"><div><p className="eyebrow">БУДУЩИЙ АВТОРСКИЙ ПРОЕКТ</p><h2>«Авторская история»</h2><p>Персональная услуга находится в разработке. Можно оставить предварительную заявку — условия появятся позднее.</p></div><button className="btn primary" onClick={()=>setForm(true)}>Оставить заявку</button></section>
   <section id="contact" className="contact"><div><p className="eyebrow">ОСТАВАЙТЕСЬ НА СВЯЗИ</p><h2>Читайте.<br/><i>Слушайте.</i><br/>Приходите в театр.</h2></div><div className="contact-links"><a href="mailto:author@example.com">author@example.com</a><a href="#">Социальные сети автора</a><a href="#">Платформа для донатов</a><a href="#">Сайт театра</a></div></section>
  </main>
  <footer>© {new Date().getFullYear()} Анастасия Алексеевна <span>·</span> Литературное пространство</footer>
  <AnimatePresence>{book&&<Modal onClose={()=>setBook(null)}><p className="eyebrow">ОТРЫВОК</p><h2>{book.title}</h2><p>{book.excerpt}</p><hr/><p>Выберите формат электронной книги:</p><div className="format-buttons"><button onClick={()=>alert('Здесь подключается Stripe Checkout')}>EPUB</button><button onClick={()=>alert('Здесь подключается Stripe Checkout')}>PDF</button><button onClick={()=>alert('Здесь подключается Stripe Checkout')}>MOBI</button></div><button className="btn primary full" onClick={()=>alert('Подключите Stripe Checkout на backend')}>Перейти к оплате · {book.price}</button></Modal>}{form&&<Modal onClose={()=>{setForm(false);setSent(false)}}><p className="eyebrow">КОНТАКТ</p><h2>Связаться с автором</h2>{sent?<p className="success">Спасибо! Заявка подготовлена к отправке.</p>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}><input required placeholder="Имя и фамилия"/><input required type="email" placeholder="E-mail"/><input placeholder="Телефон"/><select defaultValue=""><option value="" disabled>Удобный способ связи</option><option>Email</option><option>Телефон</option><option>Telegram</option></select><textarea required rows="5" placeholder="Описание идеи / истории"></textarea><button className="btn primary full">Отправить заявку</button></form>}</Modal>}</AnimatePresence>
 </div>
}
function Modal({children,onClose}){return <motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={e=>e.target===e.currentTarget&&onClose()}><motion.div className="modal" initial={{y:30,opacity:0}} animate={{y:0,opacity:1}} exit={{y:30,opacity:0}}><button className="close" onClick={onClose}>×</button>{children}</motion.div></motion.div>}
createRoot(document.getElementById('root')).render(<App/>);
